spring:
  datasource:
    username: root
    password: My!phon3
    url: jdbc:mysql://localhost:3306/stayIn_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

security:
  jwt:
    jwtSecret: 567890123456789436576799420245049972002781236790123
    expirationInMils: 3600000

